#!/usr/bin/env node
/**
 * Downloads Excalidraw's Xiaolai CJK fallback slices + generates @font-face CSS
 * matching packages/excalidraw/fonts/Xiaolai/index.ts (offline parity with excalidraw.com).
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const INDEX_URL =
  "https://raw.githubusercontent.com/excalidraw/excalidraw/master/packages/excalidraw/fonts/Xiaolai/index.ts";
const FONT_BASE =
  "https://raw.githubusercontent.com/excalidraw/excalidraw/master/packages/excalidraw/fonts/Xiaolai/";
const OUT_DIR = path.join(ROOT, "static/fonts/xiaolai");
const OUT_CSS = path.join(ROOT, "src/styles/xiaolai-font.css");

async function fetchText(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${url} -> ${r.status}`);
  return r.text();
}

async function fetchBuf(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${url} -> ${r.status}`);
  return Buffer.from(await r.arrayBuffer());
}

function parseIndex(indexText) {
  const importRe = /import (_\w+) from "\.\/([^"]+\.woff2)"/g;
  /** @type {Map<string, string>} */
  const varToFile = new Map();
  let m;
  while ((m = importRe.exec(indexText))) {
    varToFile.set(m[1], m[2]);
  }

  const bodyStart = indexText.indexOf("export const XiaolaiFontFaces");
  const bodyEnd = indexText.lastIndexOf("];");
  const body = indexText.slice(bodyStart, bodyEnd);

  /** Matches both `{ uri: _0,` and `{ uri: _181,` with any indentation / newlines before `uri`. */
  const re = /\{\s*uri:\s*(_\w+),\s*descriptors:\s*\{\s*unicodeRange:\s*(?:\n\s*)?"([^"]+)"/g;
  /** @type {{ varName: string; range: string; file: string }[]} */
  const entries = [];
  while ((m = re.exec(body))) {
    const varName = m[1];
    const range = m[2];
    const file = varToFile.get(varName);
    if (!file) {
      console.warn("missing import for", varName);
      continue;
    }
    entries.push({ varName, range, file });
  }

  if (entries.length === 0) {
    throw new Error("No Xiaolai font-face entries parsed — check index.ts format");
  }

  return { varToFile, entries };
}

function buildCss(entries) {
  const lines = [
    "/* Generated by scripts/vendor-xiaolai.mjs — CJK hand-drawn fallback (FONT_FAMILY_FALLBACKS.Xiaolai). */",
    "/* Font: Xiaolai / 小賴 (SIL OFL); upstream: excalidraw/packages/excalidraw/fonts/Xiaolai */",
    "",
  ];
  for (const { file, range } of entries) {
    lines.push("@font-face {");
    lines.push('  font-family: "Xiaolai";');
    lines.push("  font-style: normal;");
    lines.push("  font-weight: 400;");
    lines.push("  font-display: swap;");
    lines.push(`  src: url("/fonts/xiaolai/${file}") format("woff2");`);
    lines.push(`  unicode-range: ${range};`);
    lines.push("}");
    lines.push("");
  }
  return lines.join("\n");
}

async function main() {
  console.log("Fetching index.ts …");
  const indexText = await fetchText(INDEX_URL);
  const { entries, varToFile } = parseIndex(indexText);
  console.log(`Parsed ${entries.length} @font-face entries, ${varToFile.size} woff2 imports.`);

  fs.mkdirSync(OUT_DIR, { recursive: true });

  const uniqueFiles = [...new Set(entries.map((e) => e.file))];
  for (const file of uniqueFiles) {
    const dest = path.join(OUT_DIR, file);
    if (fs.existsSync(dest) && fs.statSync(dest).size > 0) {
      continue;
    }
    const url = FONT_BASE + file;
    process.stdout.write(`  ${file} … `);
    const buf = await fetchBuf(url);
    fs.writeFileSync(dest, buf);
    console.log(`${buf.length} B`);
  }

  fs.mkdirSync(path.dirname(OUT_CSS), { recursive: true });
  fs.writeFileSync(OUT_CSS, buildCss(entries), "utf8");
  console.log(`Wrote ${OUT_CSS}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
